### PR TITLE
KA weapons poison gas grenades compatibility

### PR DESCRIPTION
**Pull request by nicoman35**
| Q | A |
| --- | --- |
| Bug fix? |  no |
| New feature? |  no  |
| Needs wipe? | no  |
| Fixed issues | #...  |

### Description:

When using poison gas grenades or grenade launcher poison gas grenades from the KA Weapons Pack, killed civilians will not be counted as killed by the player.
This is changed with the lines added.
To work correctly, not the original https://steamcommunity.com/sharedfiles/filedetails/? id=1369953203 KA Weapons Pack has to be used, but the version changed by me (here the link to it, as soon as I uploaded it on Steam)

### Content:
- [ ] Content part

### Successfully tested on:
- [ x] Local MP
- [ ] Dedicated MP

### Compatibility checked with:
* ACE
* Mod XYZ

### CODE REVIEW

**Comment by Wyqer** [comment]
I don't see any logic changes or similar. Just an additional variable and message/string to point out something was by poison gas. The implemented variable isn't even used anywhere in the framework. Guess you use it in your mod derivative.
With this you could also just add it to your derivative of the mod completely instead of putting something in the KP Liberation framework and something in your mod derivative. Speaking of that, I haven't seen any license or similar on the steam mod page. You're sure that you're even allowed to create a derivative of that mod? Beside of the fact that you can't really publish it on the workshop due to the steam subscriber agreement.
Just to keep in mind, to prevent you from any headache due to not getting permissions or similar.

**Comment by nicoman35** [comment]
Regarding the permission, I already asked KP for it, just like a bunch of other guys did. He did not answer any of our requests. Some of them published their own versions, and KA did nothing. Also, he did not interdict any republishing. So I guess either he does not care or he is ok with it. Of course, if he would interdict anything, I would take it offline or make it private.
As for the changes to KP files, I made it the way I thought it would be best and easiest. And the way it produced least headache for me. This included the changes of KP files.

**Comment by Wyqer** [comment]
> He did not answer any of our requests. Some of them published their own versions, and KA did nothing. Also, he did not interdict any republishing. So I guess either he does not care or he is ok with it.

That's not how it works. If he says nothing or doesn't reply it doesn't mean it's ok. It's exactly the opposite. But that's something you've to take care of, not me. Just as a heads up, that you might come in trouble with this way.

Concerning the additions, we won't merge it due to the reasons stated in the first commit. It's working in your community well for your players and that's a good thing. I just don't think that adding some "loose ends" in the mission is the best and clean way to achieve what you've done. I would still recommend you just add it to your mod derivative completely, as it would work fine.

**Comment by nicoman35** [comment]
Ok Wyqer. I followed your lead.
 I asked him on Twitter. He's Chinese and thus has some... 'special' relation to copying things from other people. From what I understood from him, he has no problem with my derivate.

And I moved all needed additions into my derivate. I admit it is cleaner and better this way.

**Pull request closed without merging**
