### PR TITLE
v0.96.5 - Update build tool

### PR DESCRIPTION
**Pull request by veteran29**
| Q | A |
| --- | --- |
| Bug fix? |  no |
| New feature? | yes  |
| Needs wipe? | no  |
| Fixed issues | - |

### Description:

Adds `mapDisplay` property to build tool configuration. Optional property for maps that have "not pretty" config name.
Sets value of ~~`STR_MISSION_VERSION`~~`STR_MISSION_TITLE` on build to `CTI 34 KP Liberation ${preset.mapDisplay || preset.map} ${version}`, version is fetched from `STR_MISSION_VERSION`.

### Content:
- [x] Set mission title in stringtable depending on currently built mission
- [x] Add `mapDisplay` property where sensible

### CODE REVIEW

**Comment by Wyqer** [comment]
> Sets value of STR_MISSION_VERSION on build
I guess you mean `STR_MISSION_TITLE`?

**Comment by veteran29** [comment]
@Wyqer Build will fail as you've added configs for maps that are not there yet.

**Comment by veteran29** [comment]
> > Sets value of STR_MISSION_VERSION on build
> > I guess you mean `STR_MISSION_TITLE`?

Yeah, my bad.

**Comment by Wyqer** [comment]
> 
> 
> @Wyqer Build will fail as you've added configs for maps that are not there yet.

**Pull request merged**
