### PR TITLE
v0.96.8 bugfix infantry battlegroups

### PR DESCRIPTION
**Pull request by nicoman35**
Fix. Only one of the created infantry battlegroups moved towards designated target.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? |  no  |
| Needs wipe? | no  |

### Description:

When infantry only counter attack battlegroups are spawned, only one of the created battlegroups are charging towards their designated target. This patch should change this and let all spawned battlegroups move towards target.

### Content:
- [ ] Content part

### Successfully tested on:
- [ ] Local MP
- [ ] Dedicated MP

### CODE REVIEW

**Review by mwpowellhtx — COMMENTED** [review]
Genuinely curious about this change... So new AI is being spawned every time a new `_grp` is pushed onto the `_bg_groups` array? How is that any different than simply spawning the AI when we see the `_grp`? Besides introducing potential to miss the correct AI execution? i.e. assuming the scheduler sees `spawn` in the correct order, which I do not think is guaranteed, IIRC.

**Comment by mwpowellhtx** [comment]
I see what is going on with the inner group and trailing group being created. Assuming the count is the desired count, why not just create the group and be done with it? Then there is also a potential for every 8th group to be created only?

**Comment by nicoman35** [comment]
The orignial version had the bug. I fixed it, and I could play with working infantry assaults. Given the fact, that I am an amateur coder, there is a better solution for sure. So go ahead and pull request your version.

**Comment by Beeperz** [comment]
Have tested this edit on my server with 0.96.7, looks like work good.

**Comment by some-evil-kitty** [comment]
I think this one is redundant now.

**Comment by veteran29** [comment]
Superseded by #942

**Pull request closed without merging**
