### PR TITLE
Update setUnitLoadout to CBA_fnc_setLoadout

### PR DESCRIPTION
**Pull request by Thatguy553**
- Updated open_arsenal.sqf and redeploy_manager.sqf to use CBA_fnc_setLoadout.

- Created config file bool variable to allow easy change of CBA_fnc_setLoadout's third param to refill mags.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no  |
| Needs wipe? | no  |

### Description:

Basically updated the vanilla `setUnitLoadout` used for ace loadouts to instead use `CBA_fnc_setLoadout`.

### Content:
- [x] Fix error causing new ACE loadouts to no longer be compatible with liberation.

### Successfully tested on:
- [x] Local MP
- [x] Dedicated MP

### CODE REVIEW

**Comment by TACHarsis** [comment]
Please merge this!

**Review by some-evil-kitty — APPROVED** [review]
Tested, looks good

**Review by some-evil-kitty — APPROVED** [review]
Looking good

**Review by veteran29 — APPROVED** [review]
Code LGTM

**Comment by TACHarsis** [comment]
> Please merge this!

Just took a year 😌

**Pull request merged**
