### PR TITLE
Refactor Vehicle Permissions to event handler and clean code

### PR DESCRIPTION
**Pull request by ColinM9991**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| Needs wipe? | no |
| Fixed issues |  |

### Description:

* Refactored Vehicle Permissions script to be an event handler rather than a while loop.
* Added permissible roles to allow players to enter certain parts of a vehicle for transport reasons
* Refactored code to be somewhat cleaner and remove repeated code

I have flattened any whitespace in this commit as you can see, however I am happy to add whitespace in to follow the seemingly existent standard if desired. The reason I removed whitespaces is because, in my opinion, whitespace does not make code more readable - clean code makes readable code.

I've also deleted and gitignored the package-lock.json file because this shouldn't be source controlled as it's regenerated on each PC which builds using TypeScript.

### Successfully tested on:
- [X] Local MP Vanilla
- [ ] Dedicated MP Vanilla

### Compatibility checked with:

This does not affect any modular functionality and is part of the base game, this should not affect any mods.

### CODE REVIEW

**Comment by ColinM9991** [comment]
Closing this because I've just noticed your Sprint 9 branch already refactors the permission system, and the vehicle permission system.

**Comment by Wyqer** [comment]
Yeah, the old framework won't be maintained anymore, as the code is a patchwork of many contributors and have a lot possibilities for improvements. That's the reason why we started a full refactoring of the mission code from scratch. After 0.97 official release as stable, we'll appreciate any contributions. Until then, patience and following the development would be the best.
In any way many thanks for your effort and willingness to contribute something to the project.

**Comment by ColinM9991** [comment]
What timeline are you guys working toward for releasing 0.97? Having looked at the new code, it is definitely cleaner, more maintainable and extendable.

**Comment by Pi123263** [comment]
Iirc the only timeline is somewhere in 2019, but nothing else yet.

**Comment by Wyqer** [comment]
Reopened due to 0.96.4 (Global Mobilization Update for legacy framework)

**Comment by ColinM9991** [comment]
@Wyqer In checking this against the implementation that you guys did, the only thing that's missing is the `SeatSwitchedMan` event handler, as currently' somebody could enter as a permitted role then switch seats to bypass the check.

**Comment by Wyqer** [comment]
Wow, haven't expected that fast response upon an reopened PR from january ^^
Thanks for that.
You could, if you like, join the Discord and have a talk with @veteran29 (who will do the review for your PR) in the contributors channel there.
Just as clarification, it's not for the new framework. It's for the planned update for the legacy framework, which will come nlt than friday this week.
Ref: #598

**Comment by veteran29** [comment]
@ColinM9991 Could you create branch like `permissions-cleanup` and change it to be a base for this PR? I can't add my own edits to PR if it's based on protected/master branch.

**Comment by ColinM9991** [comment]
I've been staring at this PR since January, just waiting :-)

I understand that, the new framework and implementation is much more superior.

What time suits you guys for a chat on Discord? I'm usually at work 9-4 and then gym afterwards so can squeeze some time in, I can update & test the `SeatSwitchedMan` changes tomorrow as that EH will mostly use this same script anyway and just refactor the script to retrieve the `assignedVehicleRole`.

**Comment by veteran29** [comment]
Your fork. Just create new branch at tip of this branch and set it as base for this PR. 

This will allow me to push commits here, I'll add `SeatSwitchedMan` EH and maybe some small optimizations if I find any.

**Comment by ColinM9991** [comment]
To update the source branch for a pull request, you must create a new pull request.

#605

**Pull request closed without merging**
