### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by DjHaski**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| Needs wipe? | no |
| Fixed issues | no |

### Description:
Fixed more typos and translations ;)
Also, I edited my name, because I am actually **Dj_Haski** 😮

Feel free to suggest edits.

### Successfully tested on:
- [x] Local MP

### CODE REVIEW

**Comment by Wyqer** [comment]
Thanks for providing the localization updates.
Could you please use a branch based on the 0.96.7 branch for a PR to prevent merge conflicts. Also please add a line to the changelog with your contribution :)

**Comment by DjHaski** [comment]
> 
> 
> Thanks for providing the localization updates.
> Could you please use a branch based on the 0.96.7 branch for a PR to prevent merge conflicts. Also please add a line to the changelog with your contribution :)

Yep, I already noticed, that I pushed to master, sorry ;( I will add line to the changelog later.

**Comment by DjHaski** [comment]
Damn, I am really messed up this PR 😟 I hope everything is okay now.

**Comment by veteran29** [comment]
It is 👍 just the changelog entry.

**Pull request merged**
