### PR TITLE
SFP Preset

### PR DESCRIPTION
**Pull request by Dahlgren**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| Needs wipe? | no |
| Fixed issues |  |

### Description:

Preset for https://steamcommunity.com/sharedfiles/filedetails/?id=826911897

### Content:
- [x] Content part

### Successfully tested on:
- [ ] Local MP
- [ ] Dedicated MP

### CODE REVIEW

**Comment by Wyqer** [comment]
Looks promising and you've already added an arsenal preset, that's great. 👍 
What did you've still planned for the PR? Enemy preset? Just asking due to the draft state. :)

**Comment by Dahlgren** [comment]
We haven't played with this preset for quite a while, I should probably verify that it still works as intended. There are some leftover commented RHS stuff as well which should probably be cleaned up

**Comment by Wyqer** [comment]
Any updates on this?

**Comment by Dahlgren** [comment]
Both desert and woodland should be cleaned up now

**Pull request merged**
